theme: minima
title: Not a blog. A site in construction. 
author: Laura Sinisterra
email: emailllll
description: > # this means to ignore newlines until "baseurl:"
  site site site something something something

# social links
twitter_username: lauracsc_ # DO NOT include the @ character, or else the build will fail!
github_username:  laurasinisterra # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
